### ISSUE TITLE
Documentation: wrong platform in air_quaility example

### ISSUE THREAD

**Issue by rensenti** [kpisacic/EkoKartaZg-home-assistant-custom-component#3]
Hello,

the platform should be 'eko_karta_zagreb' in the example, it's 'eko_karta_zg' at the moment.

Btw, GREAT job on the integrations, thank you for sharing them!

pozdrav :)

**Comment by kpisacic** [comment]
Thnx, updated!

**Comment by kpisacic** [comment]
Updated README
